### ISSUE TITLE
Setup Branch Protection Rules

### ISSUE THREAD

**Issue by Benjamin-Frost** [hpi-dhc/PharMe#12]
Once this organization has been upgraded to Pro, Team, or Enterprise, setup Branch Protection.

- [x] Protect `main` branch
- [x] Require a pull request before merging (TBD: One or two approvals)
- [x] Require status checks to pass before merging 
- [x] Require branches to be up to date before merging
