### ISSUE TITLE
Make Repo Public

### ISSUE THREAD

**Issue by dieknolle3333** [hpi-dhc/PharMe#159]
## before (@dieknolle3333 )

- [x] find all personal data in issues, issue histories, dangling commits, ref logs, etc.
- [x] move data we still need to google drive 
- [x] ask tamara for deletion of issues
- [x] check with gitleaks (@Toalaah)

## after

- [x] #12
- [x] #160 
- [x] #161 
- [x] #164
- [x] #121 (move to wiki & close)
