### ISSUE TITLE
Store and display recent searches

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/PharMe#166]
## Tasks:
- [ ] Store which medications were opened
- [ ] Display recently opened medications
- [ ] Make recent search entries deletable
