### ISSUE TITLE
Implement "Cache" for accessed medications

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/PharMe#169]
## Tasks
- [ ] cache list of medications initially loaded
- [ ] cache medication details on first access
- [ ] update cache if smartphone is online
