### ISSUE TITLE
`anni`: text bricks

### ISSUE THREAD

**Issue by jannis-baum** [hpi-dhc/PharMe#338]
Text bricks are predefined components that are used to create texts for annotations, namely

- a medication's patient-friendly drug class & indication and
- a medication-phenotype combination's implication & recommendation.

The creation of annotation texts is strictly limited to combinations of bricks to ensure consistency and enable easy multi-language support without the need of the maintainer having to know more than one supported language. Bricks can also include placeholders such as a given medication's name, but this won't be implemented with this issue.

### Tasks

- [x] database model for multi-language text bricks
- [x] CRUD-interface for text bricks
  - [x] list of bricks organized by category with settable display language
  - [x] bricks can be defined in multiple languages (list of available languages hardcoded)
- [x] add *text brick* and *annotation* to glossary
- [x] add in-app explanations & terminology
