### ISSUE TITLE
`anni`: annotations

### ISSUE THREAD

**Issue by jannis-baum** [hpi-dhc/PharMe#341]
An *annotation* defines a patient-friendly drug class & indication for a medication and an  implication & recommendation for a medication-phenotype combination. All of these texts are built using text bricks.

### Tasks

- [x] create database model(s) to store annotations
  - [x] associable with Annotation Server medications through their RxCUI and phenotypes through string matching
  - [x] store text(s) as references to bricks
  - [x] method that evaluates text by language (lookup + fill out placeholders)
- [x] implement placeholders into Text Brick editor
  - [x] also for variable text
- [x] CRUD for annotations matched with lists from #339 
  - [x] edit by drag&dropping Bricks
  - [x] save to Interface
  - [x] save to Server
  - [x] sync annotations after fetching
    - ~~[ ] give warning in control panel in case some annotations couldn't be matched, show an option to delete them~~
- [x] remove Google Sheet stuff from Annotation Server and add post endpoint to upload annotations
- [x] edit guideline warning level
