### ISSUE TITLE
Include active medications

### ISSUE THREAD

**Issue by tamslo** [hpi-dhc/PharMe#441]
It should be possible to include active medications in PharMe.

### Original brain storming

- like "Report" but filtered by active medications; could even be same tab with different filter options)
- Startbildschirm für Suche (nur noch ein Tab)
- Sort by status (red, yellow, green)
- Maybe: Sort by medication group option [might be working in search]
- Default filters; show active filters; maybe add medication group as filters
- Also see #174 

### Todos

* [x] ~~Import from Sinai infrastructure (expected: array of Rx CUIs, however, not verified yet; maybe dosages)~~ moved to #462
* [x] initialize critical medications as active/starred
* [x] star/unstar medications
* [x] filter search by active medications
* [x] Add warning level highlighting and icons to search (should also think about short descriptions)
* [x] ~~Have tab "my medications"~~ replace tabs *Search* and *Report* by new common tab *Medications*
  * [x] defaults to show starred medications
  * [x] has search in top
  * [x] named "Medications" with suitable icon
