### ISSUE TITLE
Investigate on app behavior for unknown lookups and implement desired behavior

### ISSUE THREAD

**Issue by tamslo** [hpi-dhc/PharMe#620]
Lookups are fetched from CPIC and matched with users' diplotypes from the lab. If users have no results or unknown results for drug guidelines, these should be mapped to Indeterminate.

**Tasks**

* [x] Define desired and investigate current app behavior (see [wiki](https://github.com/hpi-dhc/PharMe/blob/main/docs/feature-discussion/App-behavior-in-case-of-missing-data.md))
* [x] Discuss with Aniwaa
* [x] Refine app behavior definition
* [x] Add collected tasks to pre-processing script issue (#657)
* [x] Create other emerging issues (how to show in app)

**App behavior**

See [wiki page](https://github.com/hpi-dhc/PharMe/blob/main/docs/App-behavior-when-lookups-unknown.md)

**What should be caught by the pre-processing script**:

* Unknown gene – make clear that  guidelines cannot be shown; drug guideline will be Indeterminate, independent if present in Anni (? – should test; should not happen)
* Unknown diplotype but known gene – make clear that gene and diplotype will be shown in list but all drug guidelines will be Indeterminate (? – should test;  can happen but should double-check those cases)
