### ISSUE TITLE
Get (custom) lookups from Anni

### ISSUE THREAD

**Issue by tamslo** [hpi-dhc/PharMe#633]
Currently, the app relies on (and fetches) CPIC lookupkeys to match lab data to guidelines. If external annotations use genes/genotypes CPIC does not include, PharMe will not be able to match these.

Would also ensure that lookups and annotation versions are kept in sync.

For Health-X dataLOFT it might be interesting to remove unnecessary non-Gaia-X resources from the app.

**Tasks**:
* [ ] Move lookup query to Anni & integrate with data initialization
* [ ] Fetch lookups from Anni in app when updating medications
* [ ] Add custom lookups to data repository and combine in Anni
* [ ] Store hash as version and update in app if content changed

**Comment by tamslo** [comment]
Will not be relevant for study
