### ISSUE TITLE
Create validation script for lab data

### ISSUE THREAD

**Issue by tamslo** [hpi-dhc/PharMe#657]
Input: data that should be sent to app

Output: warnings if assumptions are not met

_:warning: Will be implemented in study backend (Sinai fork)_

**Tasks**

- [ ] Test that data is in format expected by the app
- [ ] Check whether genes that occur multiple times are always genes with "positive/negative" result for specific alleles in the fomat "<allele_name_without_spaces> [positive/negative]"
- [ ] Check whether gene/diplotype lookups are included in CPIC
- [ ] Check whether CPIC phenotypes and lab report phenotypes (required!) match
- [ ] Check that genes names do not contain spaces
- [ ] Double-check results explicitly for comprehension questionnaire medications: **ibuprofen, simvastatin, citalopram, clopidogrel**
